
tasks:
  - name: initialize
    before: |
      echo "🤔 before"
    init: |
      echo "🚀 init"
      cd cruise0-spa
      npm install
      clear
      url=$(gp url 3000)
      echo "$url"
      echo "$url/cruise0_small.png"


ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - aaron-bond.better-comments
